package dev.gulp.api.spi;

import dev.gulp.api.data.JsonObject;
import dev.gulp.api.entity.Component;

/**
 * Reads and writes the {@code @Save} fields of one persistent component class. Generated by {@code gulp-processor}
 * for each {@code @ComponentInfo} class; used by the engine when saving and loading worlds.
 *
 * <pre>{@code
 * // generated
 * final class Wallet$State implements ComponentState<Wallet> {
 *     public JsonObject save(Wallet c) { return JsonObject.builder().put("coins", c.coins).build(); }
 *     public void load(Wallet c, JsonObject json) { c.coins = ...; }
 * }
 * }</pre>
 *
 * @param <C> the component class
 */
public interface ComponentState<C extends Component> {

    /**
     * Writes the saved fields.
     *
     * @param component the component
     * @return one member per field
     */
    JsonObject save(C component);

    /**
     * Restores the saved fields; members that are missing keep the field's current value.
     *
     * @param component the component
     * @param json what {@link #save} wrote
     */
    void load(C component, JsonObject json);
}
