package dev.gulp.api.spi;

import dev.gulp.api.event.Event;
import dev.gulp.api.event.EventPriority;
import dev.gulp.api.event.Listener;
import java.util.function.Consumer;

/**
 * Dispatcher generated by {@code gulp-processor} for a {@link Listener} class ({@code <Name>$Handlers}): it hands the
 * engine one direct-call handler per {@code @EventHandler} method, including inherited ones.
 *
 * <pre>{@code
 * // generated for DamageListener
 * final class DamageListener$Handlers implements ListenerHandlers<DamageListener> {
 *     public void register(DamageListener l, HandlerSink sink) {
 *         sink.handler(EntityDamageEvent.class, EventPriority.HIGH, true, l::onDamage);
 *     }
 * }
 * }</pre>
 *
 * @param <L> the listener type
 */
public interface ListenerHandlers<L extends Listener> {

    /**
     * Reports the handlers of one listener instance.
     *
     * @param listener the listener
     * @param sink receives the handlers
     */
    void register(L listener, HandlerSink sink);

    /**
     * Receives handlers from generated dispatchers.
     *
     * <pre>{@code
     * sink.handler(TickEndEvent.class, EventPriority.NORMAL, false, listener::onTickEnd);
     * }</pre>
     */
    interface HandlerSink {

        /**
         * Reports one handler.
         *
         * @param <E> the event type
         * @param type the event class of the method parameter
         * @param priority from the annotation
         * @param ignoreCancelled from the annotation
         * @param handler calls the method
         */
        <E extends Event> void handler(
                Class<E> type, EventPriority priority, boolean ignoreCancelled, Consumer<? super E> handler);
    }
}
