package dev.gulp.api.spi;

import java.util.List;

/**
 * The values of a module's {@link dev.gulp.api.module.ModuleInfo}, generated by {@code gulp-processor} so the engine
 * does not read annotations at runtime.
 *
 * <pre>{@code
 * new ModuleDescriptor("coin", List.of("player", "hud"), List.of(), true)
 * }</pre>
 *
 * @param id the module id
 * @param dependsOn required modules
 * @param softDependsOn optional modules loaded first if present
 * @param enabledByDefault whether the module is enabled at startup
 */
public record ModuleDescriptor(
        String id, List<String> dependsOn, List<String> softDependsOn, boolean enabledByDefault) {

    /** Copies the lists. */
    public ModuleDescriptor {
        dependsOn = List.copyOf(dependsOn);
        softDependsOn = List.copyOf(softDependsOn);
    }
}
