package dev.gulp.core.milestone;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.assertj.core.api.Assertions.assertThat;

import dev.gulp.api.Game;
import dev.gulp.api.GameSettings;
import dev.gulp.api.event.EventHandler;
import dev.gulp.api.event.Listener;
import dev.gulp.api.event.lifecycle.TickEndEvent;
import dev.gulp.api.module.GameModule;
import dev.gulp.api.module.ModuleInfo;
import dev.gulp.api.module.ModuleState;
import dev.gulp.backend.headless.HeadlessRunner;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Stage 1 milestone (spec, section 22): a headless game with two modules — a dependency, a listener,
 * {@code every(20)} and a config read; disabling a module cancels its tasks and listeners.
 */
class MilestoneTest {

    /** Pays income every second (20 ticks at 20 TPS); amounts come from config/economy.yml. */
    @ModuleInfo(id = "economy")
    public static final class EconomyModule extends GameModule {
        int coins;
        final List<Long> paydays = new ArrayList<>();

        @Override
        public void onEnable() {
            coins = config().getInt("start", 0);
            int income = config().getInt("income", 1);
            every(20, () -> {
                coins += income;
                paydays.add(engine().tick());
            });
        }
    }

    /** Depends on the economy; buys an item whenever there is enough money at the end of a tick. */
    @ModuleInfo(id = "shop", dependsOn = "economy")
    public static final class ShopModule extends GameModule {
        final List<String> bought = new ArrayList<>();

        @Override
        public void onEnable() {
            listen(new ShopListener(this));
        }
    }

    /** Listener dispatched through code generated by gulp-processor. */
    public static final class ShopListener implements Listener {
        private final ShopModule shop;

        ShopListener(ShopModule shop) {
            this.shop = shop;
        }

        @EventHandler
        void afterTick(TickEndEvent event) {
            EconomyModule economy = shop.require(EconomyModule.class);
            int price = shop.config().getInt("price", 100);
            if (economy.coins >= price) {
                economy.coins -= price;
                shop.bought.add("item@" + event.tick());
            }
        }
    }

    static final class MarketGame extends Game {
        final EconomyModule economy = new EconomyModule();
        final ShopModule shop = new ShopModule();

        @Override
        public String id() {
            return "market";
        }

        @Override
        public void configure(GameSettings settings) {
            settings.ticksPerSecond(20).modules(shop, economy);
        }

        @Override
        public void onStart() {}
    }

    @Test
    void twoModulesWithDependencyListenerRepeatingTaskAndConfig() {
        MarketGame game = new MarketGame();
        HeadlessRunner runner = HeadlessRunner.start(game, backend -> {
            backend.files().putAsset("market/config/economy.yml", "start: 10\nincome: 30\n".getBytes(UTF_8));
            backend.files().putAsset("market/config/shop.yml", "price: 50\n".getBytes(UTF_8));
            backend.loop().setFrameNanos(1_000_000_000L / 20); // one frame per tick at 20 TPS
        });
        runner.step(1);

        assertThat(runner.engine().modules().ids()).containsExactly("economy", "shop");
        assertThat(game.economy.coins).isEqualTo(10);

        runner.step(60); // three seconds
        assertThat(game.economy.paydays).containsExactly(20L, 40L, 60L);
        // 10 + 30 = 40 at tick 20 (no purchase), 70 at tick 40 -> buy (20), 50 at tick 60 -> buy (0)
        assertThat(game.shop.bought).containsExactly("item@40", "item@60");
        assertThat(game.economy.coins).isZero();

        runner.engine().modules().disable("economy");
        assertThat(runner.engine().modules().state("shop")).isEqualTo(ModuleState.DISABLED);
        assertThat(runner.engine().modules().state("economy")).isEqualTo(ModuleState.DISABLED);
        assertThat(runner.engine().registrationsOf(game.economy)).isZero();
        assertThat(runner.engine().registrationsOf(game.shop)).isZero();

        runner.step(60);
        assertThat(game.economy.paydays).as("task cancelled").hasSize(3);
        assertThat(game.shop.bought).as("listener removed").hasSize(2);

        runner.stop();
    }
}
