package dev.gulp.gradle;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Stream;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.ConfigurableFileCollection;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.CacheableTask;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputFiles;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.PathSensitive;
import org.gradle.api.tasks.PathSensitivity;
import org.gradle.api.tasks.TaskAction;

/**
 * Writes {@code GameAssets}, a class with a constant for every asset, like Android's {@code R}: a typo in an asset path
 * becomes a compile error.
 *
 * <pre>{@code
 * Texture logo = assets().get(GameAssets.Textures.LOGO);
 * TextureRegion coin = assets().get(GameAssets.Sprites.COIN);
 * Font title = assets().get(GameAssets.Fonts.TITLE);
 * }</pre>
 *
 * <p>Folders become nested classes: {@code textures/} (textures), {@code sprites/} (atlas regions), {@code fonts/}
 * (fonts), {@code sounds/} (audio clips), {@code music/} (music), {@code data/}, {@code shaders/}, {@code lang/} and {@code maps/} (text); other folders give byte keys. Constant names are
 * the paths in upper case with {@code _} for separators. The engine's own {@code gulp} namespace is skipped.
 */
@CacheableTask
public abstract class GenerateAssetKeys extends DefaultTask {

    /** Creates the task; instantiated by Gradle. */
    public GenerateAssetKeys() {}

    /**
     * Returns the folders whose {@code assets} subfolders are scanned (sources and generated fonts).
     *
     * @return the folders
     */
    @InputFiles
    @PathSensitive(PathSensitivity.RELATIVE)
    public abstract ConfigurableFileCollection getResourceDirectories();

    /**
     * Returns the package of the generated class.
     *
     * @return the package name
     */
    @Input
    public abstract Property<String> getPackageName();

    /**
     * Returns the source folder that receives the class.
     *
     * @return the folder
     */
    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    /**
     * Scans the assets and writes the class.
     *
     * @throws IOException if files cannot be read or written
     */
    @TaskAction
    public void generate() throws IOException {
        // group -> constant -> key expression
        Map<String, Map<String, String>> groups = new TreeMap<>();
        for (File root : getResourceDirectories().getFiles()) {
            Path assets = root.toPath().resolve("assets");
            if (!Files.isDirectory(assets)) {
                continue;
            }
            try (Stream<Path> files = Files.walk(assets)) {
                for (Path file : files.filter(Files::isRegularFile).sorted().toList()) {
                    add(groups, assets.relativize(file).toString().replace(File.separatorChar, '/'));
                }
            }
        }
        StringBuilder source = new StringBuilder();
        String packageName = getPackageName().get();
        if (!packageName.isEmpty()) {
            source.append("package ").append(packageName).append(";\n\n");
        }
        source.append("import dev.gulp.api.asset.AssetKey;\n\n")
                .append("/** Generated by the Gulp Gradle plugin from the assets folder; do not edit. */\n")
                .append("@SuppressWarnings(\"unused\")\n")
                .append("public final class GameAssets {\n")
                .append("    private GameAssets() {}\n");
        for (Map.Entry<String, Map<String, String>> group : groups.entrySet()) {
            source.append("\n    /** Assets in the {@code ")
                    .append(group.getKey().toLowerCase(Locale.ROOT))
                    .append("} folder. */\n")
                    .append("    public static final class ")
                    .append(group.getKey())
                    .append(" {\n")
                    .append("        private ")
                    .append(group.getKey())
                    .append("() {}\n");
            for (Map.Entry<String, String> constant : group.getValue().entrySet()) {
                source.append("\n        /** {@code ")
                        .append(keyOf(constant.getValue()))
                        .append("}. */\n")
                        .append("        public static final ")
                        .append(constant.getValue())
                        .append(";\n");
            }
            source.append("    }\n");
        }
        source.append("}\n");
        Path output = getOutputDirectory().get().getAsFile().toPath();
        Path file = output.resolve(packageName.replace('.', '/')).resolve("GameAssets.java");
        Files.createDirectories(file.getParent());
        Files.writeString(file, source.toString(), StandardCharsets.UTF_8);
    }

    private static String keyOf(String declaration) {
        int start = declaration.indexOf('"');
        return declaration.substring(start + 1, declaration.indexOf('"', start + 1));
    }

    private static void add(Map<String, Map<String, String>> groups, String path) {
        int slash = path.indexOf('/');
        if (slash < 0 || path.endsWith(".manifest.json")) {
            return;
        }
        String namespace = path.substring(0, slash);
        String rest = path.substring(slash + 1);
        int folderEnd = rest.indexOf('/');
        if (namespace.equals("gulp") || folderEnd < 0) {
            return;
        }
        String folder = rest.substring(0, folderEnd);
        String inside = rest.substring(folderEnd + 1);
        String lower = inside.toLowerCase(Locale.ROOT);
        String withoutExtension = stripExtension(inside);
        String key = namespace + ":" + folder + "/" + withoutExtension;
        String group;
        String type;
        String factory;
        switch (folder) {
            case "textures" -> {
                group = "Textures";
                type = "AssetKey<dev.gulp.api.graphics.Texture>";
                factory = "texture";
            }
            case "sprites" -> {
                group = "Sprites";
                type = "AssetKey<dev.gulp.api.graphics.TextureRegion>";
                factory = "region";
            }
            case "fonts" -> {
                if (lower.endsWith(".png") || lower.endsWith(".txt")) {
                    return;
                }
                group = "Fonts";
                type = "AssetKey<dev.gulp.api.text.Font>";
                factory = "font";
                key = namespace + ":" + folder + "/" + stripFontExtension(inside);
            }
            case "sounds" -> {
                group = "Sounds";
                type = "AssetKey<dev.gulp.api.audio.AudioClip>";
                factory = "audio";
            }
            case "music" -> {
                group = "Music";
                type = "AssetKey<dev.gulp.api.audio.Music>";
                factory = "music";
            }
            case "config" -> {
                return;
            }
            case "maps" -> {
                if (lower.endsWith(".png") || lower.endsWith(".jpg") || lower.endsWith(".webp")) {
                    group = "Maps";
                    type = "AssetKey<dev.gulp.api.graphics.Texture>";
                    factory = "texture";
                    key = namespace + ":" + folder + "/" + inside;
                } else if (lower.endsWith(".tmj") || lower.endsWith(".tmx") || lower.endsWith(".ldtk")) {
                    group = "Maps";
                    type = "AssetKey<String>";
                    factory = "text";
                } else {
                    // External tile sets and levels are read through their map.
                    return;
                }
            }
            case "data", "shaders", "lang" -> {
                group = capitalize(folder);
                type = "AssetKey<String>";
                factory = "text";
            }
            default -> {
                group = capitalize(folder);
                type = "AssetKey<byte[]>";
                factory = "bytes";
                key = namespace + ":" + folder + "/" + inside;
            }
        }
        String name = constantName(key.substring(key.indexOf('/') + 1));
        Map<String, String> constants = groups.computeIfAbsent(group, g -> new TreeMap<>());
        String declaration = type + " " + name + " = AssetKey." + factory + "(\"" + key + "\")";
        if (constants.containsKey(name) && !constants.get(name).equals(declaration)) {
            name = constantName(namespace + "_" + key.substring(key.indexOf('/') + 1));
            declaration = type + " " + name + " = AssetKey." + factory + "(\"" + key + "\")";
        }
        constants.put(name, declaration);
    }

    private static String stripExtension(String path) {
        int dot = path.lastIndexOf('.');
        return dot > path.lastIndexOf('/') ? path.substring(0, dot) : path;
    }

    private static String stripFontExtension(String path) {
        return path.endsWith(".msdf.json")
                ? path.substring(0, path.length() - ".msdf.json".length())
                : stripExtension(path);
    }

    static String constantName(String path) {
        StringBuilder name = new StringBuilder();
        for (char c : path.toCharArray()) {
            name.append(Character.isLetterOrDigit(c) ? Character.toUpperCase(c) : '_');
        }
        if (name.isEmpty() || Character.isDigit(name.charAt(0))) {
            name.insert(0, '_');
        }
        return name.toString();
    }

    private static String capitalize(String folder) {
        String name = constantName(folder).toLowerCase(Locale.ROOT);
        StringBuilder result = new StringBuilder();
        boolean upper = true;
        for (char c : name.toCharArray()) {
            if (c == '_') {
                upper = true;
            } else {
                result.append(upper ? Character.toUpperCase(c) : c);
                upper = false;
            }
        }
        return result.toString();
    }
}
