package dev.gulp.core;

import dev.gulp.api.data.Codec;
import dev.gulp.api.event.Listener;
import dev.gulp.api.module.GameModule;
import dev.gulp.api.spi.GeneratedIndex;
import dev.gulp.api.spi.ListenerHandlers;
import dev.gulp.api.spi.ModuleDescriptor;
import dev.gulp.platform.PlatformModules;
import java.util.HashMap;
import java.util.Map;
import java.util.ServiceLoader;
import org.jspecify.annotations.Nullable;

/**
 * Registry of code generated by {@code gulp-processor}, read once from every {@link GeneratedIndex} on the classpath.
 * Answers {@link PlatformModules} lookups for the contracts {@link ListenerHandlers}, {@link ModuleDescriptor} and
 * {@link Codec}.
 */
public final class GeneratedModules implements PlatformModules {

    private static @Nullable GeneratedModules shared;

    private final Map<Class<?>, ListenerHandlers<?>> listeners = new HashMap<>();
    private final Map<Class<?>, ModuleDescriptor> modules = new HashMap<>();
    private final Map<Class<?>, Codec<?>> codecs = new HashMap<>();

    /** Creates an empty registry; fill it with {@link #add(GeneratedIndex)}. */
    public GeneratedModules() {}

    /**
     * Returns the registry built from all indexes found by {@link ServiceLoader}, loaded on first use.
     *
     * @return the shared registry
     */
    public static synchronized GeneratedModules shared() {
        if (shared == null) {
            GeneratedModules loaded = new GeneratedModules();
            for (GeneratedIndex index : ServiceLoader.load(GeneratedIndex.class)) {
                loaded.add(index);
            }
            shared = loaded;
        }
        return shared;
    }

    /**
     * Adds the entries of one index.
     *
     * @param index the index
     * @return this registry
     */
    public GeneratedModules add(GeneratedIndex index) {
        index.register(new GeneratedIndex.Sink() {
            @Override
            public <L extends Listener> void listener(Class<L> type, ListenerHandlers<L> handlers) {
                listeners.put(type, handlers);
            }

            @Override
            public void module(Class<? extends GameModule> type, ModuleDescriptor descriptor) {
                modules.put(type, descriptor);
            }

            @Override
            public <T> void codec(Class<T> type, Codec<T> codec) {
                codecs.put(type, codec);
            }
        });
        return this;
    }

    @Override
    public <T> @Nullable T lookup(Class<T> contract, Class<?> subject) {
        Object found;
        if (contract == ListenerHandlers.class) {
            found = listeners.get(subject);
        } else if (contract == ModuleDescriptor.class) {
            found = modules.get(subject);
        } else if (contract == Codec.class) {
            found = codecs.get(subject);
        } else {
            found = null;
        }
        return found == null ? null : contract.cast(found);
    }
}
