package dev.gulp.api.data;

import dev.gulp.api.registry.Key;
import dev.gulp.api.spi.ApiSupport;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import org.jspecify.annotations.Nullable;

/**
 * Two-way conversion between a type and {@link JsonValue}, used by configs, saved data and network messages.
 *
 * <pre>{@code
 * @Serializable
 * public record Upgrade(String name, int level, List<Key> unlocks) {}
 *
 * Codec<Upgrade> codec = Codec.of(Upgrade.class);           // generated by gulp-processor
 * JsonValue json = codec.encode(new Upgrade("dash", 2, List.of()));
 * Upgrade back = codec.decode(json);
 *
 * Codec<List<Integer>> scores = Codec.listOf(Codec.INT);
 * Codec<Difficulty> difficulty = Codec.enumOf(Difficulty.values());
 * }</pre>
 *
 * @param <T> the converted type
 */
public interface Codec<T> {

    /** {@code boolean} as a JSON boolean. */
    Codec<Boolean> BOOLEAN = of(
            JsonBoolean::of, json -> expect(json, JsonBoolean.class, "boolean").value());

    /** {@code int} as a JSON number. */
    Codec<Integer> INT =
            of(JsonNumber::of, json -> expect(json, JsonNumber.class, "number").intValue());

    /** {@code long} as a JSON number. */
    Codec<Long> LONG =
            of(JsonNumber::of, json -> expect(json, JsonNumber.class, "number").longValue());

    /** {@code float} as a JSON number. */
    Codec<Float> FLOAT = of(value -> JsonNumber.of((double) value), json ->
            (float) expect(json, JsonNumber.class, "number").doubleValue());

    /** {@code double} as a JSON number. */
    Codec<Double> DOUBLE =
            of(JsonNumber::of, json -> expect(json, JsonNumber.class, "number").doubleValue());

    /** Strings as JSON strings. */
    Codec<String> STRING =
            of(JsonString::new, json -> expect(json, JsonString.class, "string").value());

    /** Keys as {@code "namespace:path"} strings. */
    Codec<Key> KEY = STRING.xmap(Key::parse, Key::toString);

    /** Any JSON value, unchanged. */
    Codec<JsonValue> JSON = of(value -> value, json -> json);

    /**
     * Converts a value to JSON.
     *
     * @param value the value
     * @return the JSON form
     */
    JsonValue encode(T value);

    /**
     * Converts JSON to a value.
     *
     * @param json the JSON form
     * @return the value
     * @throws CodecException if the JSON does not have the expected shape
     */
    T decode(JsonValue json);

    /**
     * Returns a codec converting through this one.
     *
     * @param <R> the new type
     * @param to converts a decoded value to the new type
     * @param from converts the new type back before encoding
     * @return the derived codec
     */
    default <R> Codec<R> xmap(Function<? super T, ? extends R> to, Function<? super R, ? extends T> from) {
        Codec<T> self = this;
        return of(value -> self.encode(from.apply(value)), json -> {
            T decoded = self.decode(json);
            try {
                return to.apply(decoded);
            } catch (IllegalArgumentException e) {
                throw new CodecException(e.getMessage() == null ? "Invalid value" : e.getMessage(), e);
            }
        });
    }

    /**
     * Returns a codec that also accepts {@code null}, encoded as JSON {@code null}.
     *
     * @return the nullable codec
     */
    default Codec<@Nullable T> nullable() {
        Codec<T> self = this;
        return new Codec<>() {
            @Override
            public JsonValue encode(@Nullable T value) {
                return value == null ? JsonNull.INSTANCE : self.encode(value);
            }

            @Override
            public @Nullable T decode(JsonValue json) {
                return json.isNull() ? null : self.decode(json);
            }
        };
    }

    /**
     * Creates a codec from two functions.
     *
     * @param <T> the converted type
     * @param encoder converts a value to JSON
     * @param decoder converts JSON to a value; may throw {@link CodecException} or {@link IllegalStateException}
     * @return the codec
     */
    static <T> Codec<T> of(Function<? super T, ? extends JsonValue> encoder, Function<JsonValue, ? extends T> decoder) {
        return new Codec<>() {
            @Override
            public JsonValue encode(T value) {
                return encoder.apply(value);
            }

            @Override
            public T decode(JsonValue json) {
                try {
                    return decoder.apply(json);
                } catch (IllegalStateException e) {
                    throw new CodecException(e.getMessage() == null ? "Invalid JSON" : e.getMessage(), e);
                }
            }
        };
    }

    /**
     * Returns a codec that asks the supplier for the real codec on first use, for recursive types and generated
     * codecs that may not be registered yet.
     *
     * <pre>{@code
     * Codec<Node> node = Codec.lazy(() -> Codec.of(Node.class));
     * }</pre>
     *
     * @param <T> the converted type
     * @param supplier supplies the real codec once
     * @return the lazy codec
     */
    static <T> Codec<T> lazy(java.util.function.Supplier<? extends Codec<T>> supplier) {
        return new Codec<>() {
            private @Nullable Codec<T> delegate;

            private Codec<T> delegate() {
                Codec<T> current = delegate;
                if (current == null) {
                    current = supplier.get();
                    delegate = current;
                }
                return current;
            }

            @Override
            public JsonValue encode(T value) {
                return delegate().encode(value);
            }

            @Override
            public T decode(JsonValue json) {
                return delegate().decode(json);
            }
        };
    }

    /**
     * Returns the codec generated by {@code gulp-processor} for a {@link Serializable} record.
     *
     * @param <T> the record type
     * @param type the record class
     * @return the generated codec
     * @throws IllegalArgumentException if the class is not a processed {@code @Serializable} record
     */
    static <T> Codec<T> of(Class<T> type) {
        Codec<T> codec = ApiSupport.get().generatedCodec(type);
        if (codec == null) {
            throw new IllegalArgumentException("No generated codec for " + type.getName()
                    + ". Annotate the record with @Serializable and add gulp-processor as an annotation processor.");
        }
        return codec;
    }

    /**
     * Returns a codec for lists.
     *
     * @param <T> the element type
     * @param element the element codec
     * @return the list codec; decoded lists are unmodifiable
     */
    static <T> Codec<List<T>> listOf(Codec<T> element) {
        return of(
                list -> {
                    JsonArray.Builder builder = JsonArray.builder();
                    for (T item : list) {
                        builder.add(element.encode(item));
                    }
                    return builder.build();
                },
                json -> {
                    JsonArray array = expect(json, JsonArray.class, "array");
                    List<T> result = new ArrayList<>(array.size());
                    for (int i = 0; i < array.size(); i++) {
                        try {
                            result.add(element.decode(array.get(i)));
                        } catch (CodecException e) {
                            throw e.at("[" + i + "]");
                        }
                    }
                    return List.copyOf(result);
                });
    }

    /**
     * Returns a codec for maps with string keys, as JSON objects.
     *
     * @param <T> the value type
     * @param value the value codec
     * @return the map codec; decoded maps are unmodifiable and keep order
     */
    static <T> Codec<Map<String, T>> mapOf(Codec<T> value) {
        return of(
                map -> {
                    JsonObject.Builder builder = JsonObject.builder();
                    for (Map.Entry<String, T> entry : map.entrySet()) {
                        builder.put(entry.getKey(), value.encode(entry.getValue()));
                    }
                    return builder.build();
                },
                json -> {
                    JsonObject object = expect(json, JsonObject.class, "object");
                    Map<String, T> result = new LinkedHashMap<>();
                    for (Map.Entry<String, JsonValue> entry : object.members().entrySet()) {
                        try {
                            result.put(entry.getKey(), value.decode(entry.getValue()));
                        } catch (CodecException e) {
                            throw e.at("." + entry.getKey());
                        }
                    }
                    return java.util.Collections.unmodifiableMap(result);
                });
    }

    /**
     * Returns a codec for enum constants, encoded by {@link Enum#name()}; decoding ignores case.
     *
     * @param <E> the enum type
     * @param values all constants, usually {@code MyEnum.values()}
     * @return the enum codec
     */
    static <E extends Enum<E>> Codec<E> enumOf(E[] values) {
        E[] constants = values.clone();
        return of(value -> new JsonString(value.name()), json -> {
            String name = expect(json, JsonString.class, "string").value();
            for (E constant : constants) {
                if (constant.name().equalsIgnoreCase(name)) {
                    return constant;
                }
            }
            throw new CodecException("Unknown constant '" + name + "'");
        });
    }

    private static <J extends JsonValue> J expect(JsonValue json, Class<J> type, String name) {
        if (type.isInstance(json)) {
            return type.cast(json);
        }
        throw new CodecException("Expected a JSON " + name + " but found " + json);
    }
}
