package dev.gulp.examples.showcase;

import dev.gulp.api.event.EventHandler;
import dev.gulp.api.event.Listener;
import dev.gulp.api.event.lifecycle.PauseEvent;
import dev.gulp.api.event.lifecycle.ResumeEvent;
import dev.gulp.api.module.GameModule;
import dev.gulp.api.module.ModuleInfo;
import java.time.Duration;

/**
 * Stage 1 demo: a module with a config file, a repeating task, a sequence, a listener and a command.
 *
 * <p>Try in the terminal: {@code /hello}, {@code /timescale 2}, {@code /module disable core}, {@code /tps}.
 */
@ModuleInfo(id = "core")
final class CoreDemoModule extends GameModule {

    @Override
    public void onEnable() {
        String greeting = config().getString("greeting", "Hello");
        long every = config().getLong("report_every_seconds", 5);

        every(
                Duration.ofSeconds(every),
                () -> logger().info("Tick " + engine().tick() + ", " + Math.round(engine().tps()) + " TPS"));
        scheduler()
                .sequence()
                .wait(Duration.ofSeconds(1))
                .run(() -> logger().info(greeting))
                .start(this);
        listen(new PauseReporter());
        command("hello", ctx -> ctx.reply(greeting));
    }

    @Override
    public void onDisable() {
        logger().info("Core demo disabled; its tasks, listener and command are gone");
    }

    /** Reports pause and resume, dispatched through code generated by gulp-processor. */
    final class PauseReporter implements Listener {
        @EventHandler
        void onPause(PauseEvent event) {
            logger().info("Paused at tick " + engine().tick());
        }

        @EventHandler
        void onResume(ResumeEvent event) {
            logger().info("Resumed");
        }
    }
}
