package dev.gulp.examples.showcase;

import dev.gulp.api.graphics.Color;
import dev.gulp.api.graphics.Texture;
import dev.gulp.api.math.Rect;
import dev.gulp.api.module.GameModule;
import dev.gulp.api.module.ModuleInfo;
import dev.gulp.api.render.Draw;
import dev.gulp.api.render.RenderLayerEvent;
import dev.gulp.api.text.Font;
import dev.gulp.api.text.FontFamily;
import dev.gulp.api.text.Text;
import dev.gulp.api.text.TextAlign;
import dev.gulp.api.text.TextStyle;

/**
 * Stage 4 demo: Polish text in the three kinds of font (MSDF built in, bitmap generated by {@code packAssets},
 * dynamic from a TTF), outline and shadow, imitated bold and italic, markup effects, an inline sprite, translations,
 * and hot reload: edit {@code lang/pl_pl.json} or {@code textures/banner.png} while the game runs.
 *
 * <p>Try in the terminal: {@code /sprites 0} to hide the sprites behind the panel.
 */
@ModuleInfo(id = "text")
final class TextDemoModule extends GameModule {

    private static final Color PANEL = Color.rgba(0x10182cdd);

    private Font pixel;
    private Font dynamic;

    @Override
    public void onLoad() {
        assets().startup()
                .add(GameAssets.Fonts.PIXEL)
                .add(GameAssets.Fonts.FIRA_BOLD)
                .add(GameAssets.Textures.BANNER)
                .add(GameAssets.Sprites.COIN);
    }

    @Override
    public void onEnable() {
        pixel = assets().get(GameAssets.Fonts.PIXEL);
        dynamic = assets().get(GameAssets.Fonts.FIRA_BOLD);
        on(RenderLayerEvent.class, e -> {
            if (e.layer().name().equals("overlay")) {
                draw(e.draw());
            }
        });
    }

    private void draw(Draw draw) {
        float x = 24;
        float y = 60;
        float width = Math.min(display().width() - 48, 640);
        draw.color(PANEL)
                .roundedRect(new Rect(x - 12, y - 12, width + 24, 420), 12)
                .color(Color.WHITE);

        Texture banner = assets().get(GameAssets.Textures.BANNER);
        draw.image(banner.region(), x, y, width, 8);
        y += 20;

        draw.text(
                tr("text.title"),
                x,
                y,
                TextStyle.of(34).outline(2, Color.rgb(0x7e2553)).shadow(3, 3, Color.rgba(0x00000099)));
        y += 48;

        draw.text(tr("text.hello", 42), x, y, TextStyle.of(20));
        y += 30;
        draw.text(
                Text.of("MSDF: ")
                        .append(Text.of("pogrubiony").bold())
                        .append(", ")
                        .append(Text.of("kursywa").italic())
                        .append(" i ")
                        .append(Text.of("mały 12").size(12)),
                x,
                y,
                TextStyle.of(20));
        y += 34;

        draw.text(
                "Bitmapowy: Zażółć gęślą jaźń 0123",
                x,
                y,
                TextStyle.of(14).font(pixel).color(Color.rgb(0xffec27)));
        y += 26;
        draw.text(
                "Dynamiczny (TTF): Źdźbło, łódź, żółw — Ωμέγα, Привет",
                x,
                y,
                TextStyle.of(22).font(FontFamily.of(dynamic)).color(Color.rgb(0x00e436)));
        y += 38;

        draw.text(
                Text.markup("[wave]Fala[/wave], [shake]drżenie[/shake], [rainbow]tęcza[/rainbow], "
                        + "[pulse]puls[/pulse], [fade]zanikanie[/fade] [img=showcase:sprites/coin] moneta"),
                x,
                y,
                TextStyle.of(20));
        y += 36;

        draw.text(
                Text.markup("[color=gold]Zawijanie:[/color] długi akapit łamie się po słowach do szerokości "
                        + "prostokąta, a [b]formatowanie[/b] przechodzi przez granice linii bez przeszkód."),
                new Rect(x, y, width, 70),
                TextStyle.of(16).color(Color.rgb(0xc2c3c7)),
                TextAlign.TOP_LEFT);
        y += 80;
        draw.text(
                Text.of(tr("text.reload")),
                new Rect(x, y, width, 60),
                TextStyle.of(14).color(Color.GRAY),
                TextAlign.TOP_LEFT);
    }
}
